# Generated by Django 5.2.17 on 2026-09-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness', models.FloatField(blank=True, null=True)),
                ('fatigue', models.FloatField(blank=True, null=True)),
                ('form', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('vo2max', models.FloatField(blank=True, null=True)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_snapshot', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Снимок формы',
                'verbose_name_plural': 'Снимки формы',
            },
        ),
        migrations.CreateModel(
            name='CalendarEventCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('type', models.CharField(blank=True, default='', max_length=64)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
                ('end_date_local', models.DateTimeField(blank=True, null=True)),
                ('icu_training_load', models.FloatField(blank=True, null=True)),
                ('workout_doc', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('type', models.CharField(blank=True, default='', max_length=64)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
                ('moving_time', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('icu_training_load', models.FloatField(blank=True, null=True)),
                ('icu_intensity', models.FloatField(blank=True, null=True)),
                ('average_watts', models.FloatField(blank=True, null=True)),
                ('weighted_average_watts', models.FloatField(blank=True, null=True)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('total_elevation_gain', models.FloatField(blank=True, null=True)),
                ('compliance', models.FloatField(blank=True, null=True)),
                ('intervals_json', models.JSONField(blank=True, default=list)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('chart_path', models.CharField(blank=True, default='', max_length=512)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.telegramuser')),
                ('matched_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_activities', to='intervals.calendareventcache')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.AddIndex(
            model_name='calendareventcache',
            index=models.Index(fields=['user', 'start_date_local'], name='intervals_c_user_id_4f0979_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendareventcache',
            unique_together={('user', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'start_date_local'], name='intervals_a_user_id_fc4e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'external_id')},
        ),
    ]
