# Generated by Django 5.2.17 on 2026-09-06 10:25

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('language_code', models.CharField(blank=True, default='ru', max_length=16)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram-пользователь',
                'verbose_name_plural': 'Telegram-пользователи',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_enabled', models.BooleanField(default=True)),
                ('announce_time', models.TimeField(default='08:00')),
                ('announce_days', models.JSONField(default=list)),
                ('report_enabled', models.BooleanField(default=True)),
                ('morning_summary_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='IntervalsCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.TextField()),
                ('athlete_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Intervals credentials',
                'verbose_name_plural': 'Intervals credentials',
            },
        ),
    ]
