# Generated by Django 5.2.17 on 2026-09-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Ручное отключение до окончания срока')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-ends_at'],
                'indexes': [models.Index(fields=['user', 'ends_at'], name='users_subsc_user_id_b973ad_idx'), models.Index(fields=['is_active', 'ends_at'], name='users_subsc_is_acti_c5e320_idx')],
            },
        ),
    ]
